---

# Add authentication mechanisms to the connectors 

# Test xml tag
#- name: Test for xml tag line
#  shell: grep -c "<?xml version='1.0'"  {{ jboss_datagrid_home }}/server/conf/infinispan.xml 
#  register: test_xml_grep

# Add xml tag first line
- name: Add xml tag to infinispan.xml file
  lineinfile:
    state: present
    dest: "{{ jboss_datagrid_home }}/server/conf/infinispan.xml"
    line:  "<?xml version='1.0'  encoding='UTF-8'?>"
    insertbefore: BOF

#  when: test_xml_grep.stdout == "0"
  
 

# Secure the bindings. No PLAIN password in authentcation mechanisms 
- name: Secure Hot Hod with  SASL auth mechanisms 
  xml:
    path: "{{ jboss_datagrid_home }}/server/conf/infinispan.xml"
    xpath: /conf:infinispan/server:server/server:endpoints
    add_children:
      - hotrod-connector:
          name: hotrod
          cache-container: "default"
          worker-threads: "1000"
          _:
            - authentication:
               _:
                - sasl: 
                   mechanisms:  "SCRAM-SHA-512 SCRAM-SHA-384 SCRAM-SHA-256 SCRAM-SHA-1 DIGEST-SHA-512 DIGEST-SHA-384 DIGEST-SHA-256"
                   server-name: infinispan
                   qop: auth
    namespaces:
      conf: urn:infinispan:config:12.1
      server: urn:infinispan:server:12.1
    pretty_print: yes


#    xpath: /conf:infinispan/s:server
#    xpath: //endpoints[@socket-binding='default' and @security-realm='default']
#      - hotrod-connector:

- name: Secure REST with DIGEST auth mechanisms
  xml:
    path: "{{ jboss_datagrid_home }}/server/conf/infinispan.xml"
    xpath: /conf:infinispan/server:server/server:endpoints
    add_children:
      - rest-connector:
          name: rest
          _:
            - authentication:
                mechanisms: DIGEST
    namespaces:
      conf: urn:infinispan:config:12.1
      server: urn:infinispan:server:12.1
    pretty_print: yes

  
