---

- name: Remove transport cluster option from infinispan.xml file
  xml:
    path: "{{ jboss_datagrid_home }}/server/conf/infinispan.xml"
    xpath: /conf:infinispan/conf:cache-container/conf:transport
    state: absent
    namespaces:
      conf: urn:infinispan:config:12.1
      server: urn:infinispan:server:12.1
  when: datagrid_cluster_enabled is not defined or  datagrid_cluster_enabled == false

#    xpath: /conf:infinispan/conf:cache-container[@name='default' and @statistics='true']/transport
