---

# Tune parameters in bin/server.conf file

- name: Backp the bin/server.conf file
  copy:
    src: "{{ jboss_datagrid_home }}/bin/server.conf"
    dest: "{{ jboss_datagrid_home }}/bin/server.conf.original"
    remote_src: yes
  

- name: Set JVM Heap max Memory to 80% in server.xml
  replace: 
    path: "{{ jboss_datagrid_home }}/bin/server.conf"
    regexp: '(\s+)-Xms64m -Xmx512m(\s+)$'
    replace: '\1 -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=80\2'


- name: Set garbage collector as concuMarkSweepGC
  lineinfile:
    path: "{{ jboss_datagrid_home }}/bin/server.conf"
    line: 'JAVA_OPTS="$JAVA_OPTS -XX:+UseLargePages -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC"'
    insertbefore: '# Sample JPDA settings'


- name: Set jvm as server mode
  lineinfile:
    path: "{{ jboss_datagrid_home }}/bin/server.conf"
    line: 'JAVA_OPTS="$JAVA_OPTS -server"'
    state: present

