---

- block:
  - name: Copy JBoss DataGrid
    copy:
      src: "{{ jboss_datagrid_artifact_name }}"
      dest: "{{ jboss_datagrid_artifact_dl_dest }}"
    tags:
      - jboss_datagrid
    when: transfer_method == 'copy-from-controller' and jboss_datagrid_exists.stat.exists == false
