---

- block:
  - name: Async Download Red Hat Datagrid from Download software repo
    get_url:
      url: "{{ jboss_datagrid_artifact_source }}"
      dest: "{{ jboss_datagrid_artifact_tmp_dest }}"
      url_username: "{{ url_username | default(None) }}"
      url_password: "{{ url_password | default(None) }}"
    async: 7200
    poll: 0
    register: jboss_datagrid_download
  - name: 'Check On Red Hat AMQ Download Completion'
    async_status: jid={{ jboss_datagrid_download.ansible_job_id }}
    register: job_result3
    until: job_result3.finished
    retries: 600
    delay: 10
  - name: Set Location for Copy of Red Hat AMQ
    set_fact:
      datagrid_distribution: "{{ jboss_datagrid_artifact_tmp_dest }}"
      datagrid_remote_src: yes
  when: transfer_method == 'url' and jboss_datagrid_exists.stat.exists == false

