---
##
# Refer to JBoss Data Grid documentation
# https://access.redhat.com/documentation/en-us/red_hat_data_grid/8.2/html/data_grid_server_guide/start_server#installing_servers-quickstart
# https://access.redhat.com/solutions/3210091
##


- name: Create JBoss Data Grid Group
  group:
    name: "{{ jboss_datagrid_group }}"
    system: yes
    state: present
    gid: "400"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid User
  user:
    name: "{{ jboss_datagrid_user }}"
    comment: "JBoss Data Grid User"
    uid: "400"
    group: "{{ jboss_datagrid_group }}"
    home: "{{ jboss_datagrid_library_dest }}"
    shell: "/bin/bash"
  tags:
    - jboss_datagrid

- name: Copy JBoss Data Grid Service  File
  template:
    src: jboss-datagrid.service.j2
    dest: "/etc/systemd/system/{{ jboss_datagrid_service_file }}"
    backup: yes
    mode: "755"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid Service Log Directory
  file:
    path: "{{ jboss_datagrid_service_log_dir }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_datagrid

- name: Create JBoss Data Grid Service Runtime Data Directory
  file:
    path: "{{ jboss_datagrid_service_data_dir }}"
    owner: "{{ jboss_datagrid_user }}"
    group: "{{ jboss_datagrid_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_datagrid
