sudo: required
language: python
python:
  - "3.6"

cache: pip

env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING=False

before_install:
  - sudo apt-get update -qq

install:
  - sudo -H pip install ansible==2.9
  - sudo -H pip install docker-py
  - sudo -H pip install six --upgrade
  - sudo apt-get install -y sshpass
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles

services:
  - docker

script:
  - ansible-playbook -i tests/inventory tests/syntax-check.yml --syntax-check
